title: "MEEC Workshop at CHI 2020"
description: "Towards better methods for Momentary Emotion Elicitation and Capture."

search: false

author:
  name     : "Your Name"
  avatar   : "/logo.png"
  bio      : "Something"
  location : "Amsterdam, NL"

footer:

plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

# Defaults
